// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.5.1
// source: greet/greetpb/bidirectional.proto

package greetpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_greetpb_bidirectional_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_greet_greetpb_bidirectional_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_greet_greetpb_bidirectional_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BidiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Person *Person `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
}

func (x *BidiRequest) Reset() {
	*x = BidiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_greetpb_bidirectional_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiRequest) ProtoMessage() {}

func (x *BidiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_greetpb_bidirectional_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiRequest.ProtoReflect.Descriptor instead.
func (*BidiRequest) Descriptor() ([]byte, []int) {
	return file_greet_greetpb_bidirectional_proto_rawDescGZIP(), []int{1}
}

func (x *BidiRequest) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

type BidiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *BidiResponse) Reset() {
	*x = BidiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_greetpb_bidirectional_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiResponse) ProtoMessage() {}

func (x *BidiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greet_greetpb_bidirectional_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiResponse.ProtoReflect.Descriptor instead.
func (*BidiResponse) Descriptor() ([]byte, []int) {
	return file_greet_greetpb_bidirectional_proto_rawDescGZIP(), []int{2}
}

func (x *BidiResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_greet_greetpb_bidirectional_proto protoreflect.FileDescriptor

var file_greet_greetpb_bidirectional_proto_rawDesc = []byte{
	0x0a, 0x21, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x70, 0x62, 0x2f,
	0x62, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x62, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x22, 0x1c, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x3c, 0x0a, 0x0b, 0x42, 0x69, 0x64, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2d, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x62, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x2e,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x22, 0x26,
	0x0a, 0x0c, 0x42, 0x69, 0x64, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x51, 0x0a, 0x08, 0x42, 0x69, 0x64, 0x69, 0x43, 0x6f,
	0x6e, 0x76, 0x12, 0x45, 0x0a, 0x04, 0x42, 0x69, 0x64, 0x69, 0x12, 0x1a, 0x2e, 0x62, 0x69, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x2e, 0x42, 0x69, 0x64, 0x69, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x2e, 0x42, 0x69, 0x64, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x67, 0x72, 0x65,
	0x65, 0x74, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_greet_greetpb_bidirectional_proto_rawDescOnce sync.Once
	file_greet_greetpb_bidirectional_proto_rawDescData = file_greet_greetpb_bidirectional_proto_rawDesc
)

func file_greet_greetpb_bidirectional_proto_rawDescGZIP() []byte {
	file_greet_greetpb_bidirectional_proto_rawDescOnce.Do(func() {
		file_greet_greetpb_bidirectional_proto_rawDescData = protoimpl.X.CompressGZIP(file_greet_greetpb_bidirectional_proto_rawDescData)
	})
	return file_greet_greetpb_bidirectional_proto_rawDescData
}

var file_greet_greetpb_bidirectional_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_greet_greetpb_bidirectional_proto_goTypes = []interface{}{
	(*Person)(nil),       // 0: bidirectional.Person
	(*BidiRequest)(nil),  // 1: bidirectional.BidiRequest
	(*BidiResponse)(nil), // 2: bidirectional.BidiResponse
}
var file_greet_greetpb_bidirectional_proto_depIdxs = []int32{
	0, // 0: bidirectional.BidiRequest.person:type_name -> bidirectional.Person
	1, // 1: bidirectional.BidiConv.Bidi:input_type -> bidirectional.BidiRequest
	2, // 2: bidirectional.BidiConv.Bidi:output_type -> bidirectional.BidiResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_greet_greetpb_bidirectional_proto_init() }
func file_greet_greetpb_bidirectional_proto_init() {
	if File_greet_greetpb_bidirectional_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_greet_greetpb_bidirectional_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_greetpb_bidirectional_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_greetpb_bidirectional_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_greet_greetpb_bidirectional_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greet_greetpb_bidirectional_proto_goTypes,
		DependencyIndexes: file_greet_greetpb_bidirectional_proto_depIdxs,
		MessageInfos:      file_greet_greetpb_bidirectional_proto_msgTypes,
	}.Build()
	File_greet_greetpb_bidirectional_proto = out.File
	file_greet_greetpb_bidirectional_proto_rawDesc = nil
	file_greet_greetpb_bidirectional_proto_goTypes = nil
	file_greet_greetpb_bidirectional_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BidiConvClient is the client API for BidiConv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BidiConvClient interface {
	Bidi(ctx context.Context, opts ...grpc.CallOption) (BidiConv_BidiClient, error)
}

type bidiConvClient struct {
	cc grpc.ClientConnInterface
}

func NewBidiConvClient(cc grpc.ClientConnInterface) BidiConvClient {
	return &bidiConvClient{cc}
}

func (c *bidiConvClient) Bidi(ctx context.Context, opts ...grpc.CallOption) (BidiConv_BidiClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BidiConv_serviceDesc.Streams[0], "/bidirectional.BidiConv/Bidi", opts...)
	if err != nil {
		return nil, err
	}
	x := &bidiConvBidiClient{stream}
	return x, nil
}

type BidiConv_BidiClient interface {
	Send(*BidiRequest) error
	Recv() (*BidiResponse, error)
	grpc.ClientStream
}

type bidiConvBidiClient struct {
	grpc.ClientStream
}

func (x *bidiConvBidiClient) Send(m *BidiRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bidiConvBidiClient) Recv() (*BidiResponse, error) {
	m := new(BidiResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BidiConvServer is the server API for BidiConv service.
type BidiConvServer interface {
	Bidi(BidiConv_BidiServer) error
}

// UnimplementedBidiConvServer can be embedded to have forward compatible implementations.
type UnimplementedBidiConvServer struct {
}

func (*UnimplementedBidiConvServer) Bidi(BidiConv_BidiServer) error {
	return status.Errorf(codes.Unimplemented, "method Bidi not implemented")
}

func RegisterBidiConvServer(s *grpc.Server, srv BidiConvServer) {
	s.RegisterService(&_BidiConv_serviceDesc, srv)
}

func _BidiConv_Bidi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BidiConvServer).Bidi(&bidiConvBidiServer{stream})
}

type BidiConv_BidiServer interface {
	Send(*BidiResponse) error
	Recv() (*BidiRequest, error)
	grpc.ServerStream
}

type bidiConvBidiServer struct {
	grpc.ServerStream
}

func (x *bidiConvBidiServer) Send(m *BidiResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bidiConvBidiServer) Recv() (*BidiRequest, error) {
	m := new(BidiRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _BidiConv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bidirectional.BidiConv",
	HandlerType: (*BidiConvServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Bidi",
			Handler:       _BidiConv_Bidi_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "greet/greetpb/bidirectional.proto",
}
